### ISSUE TITLE
Subscription tests are failing

### ISSUE THREAD

**Issue by rerb** [AASHE/python-membersuite-api-client#26]
From a travis log:

======================================================================
ERROR: Get the all subscriptions for an organization
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/tests/test_subscriptions.py", line 24, in test_get_org_subscriptions_all_for_org
    org_id=TEST_MS_SUBSCRIPTION_ORG_ID)
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/subscriptions/services.py", line 59, in get_subscriptions
    start_record=start_record, verbose=verbose)
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/mixins.py", line 57, in get_long_query
    ["ObjectSearchResult"]["Objects"]["MemberSuiteObject"]
TypeError: 'NoneType' object is not subscriptable
======================================================================
ERROR: test_get_org_subscriptions_by_publication_id (membersuite_api_client.tests.test_subscriptions.SubscriptionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/tests/test_subscriptions.py", line 32, in test_get_org_subscriptions_by_publication_id
    publication_id=TEST_MS_PUBLICATION_ID)
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/subscriptions/services.py", line 59, in get_subscriptions
    start_record=start_record, verbose=verbose)
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/mixins.py", line 57, in get_long_query
    ["ObjectSearchResult"]["Objects"]["MemberSuiteObject"]
TypeError: 'NoneType' object is not subscriptable
======================================================================
FAIL: test_get_org_subscriptions_long_query (membersuite_api_client.tests.test_subscriptions.SubscriptionTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/AASHE/python-membersuite-api-client/membersuite_api_client/tests/test_subscriptions.py", line 40, in test_get_org_subscriptions_long_query
    self.assertEqual(len(subscription_list), 3)
AssertionError: 9 != 3```

**Comment by rerb** [comment]
@jamstooks These 3 tests are failing in a version of the package i'm just about to push into production -- because it's got a patch that's required before anybody can log in -- the format of MemberSuite IDs has changed, from this morning till now, important when generating a User.username.

**Comment by jamstooks** [comment]
Yes, it's likely just the outdated id's for orgs and the publication. I'll look into it.

**Comment by jamstooks** [comment]
This is fixed now with #30; PR ready whenever... but I didn't update the version so you can do that with the PR.
